"""Reusable column mixins: UUID primary keys and UTC timestamps.

Design rules (per Canonical Data Model v1.0):
  * Primary keys are PostgreSQL-native UUIDs, generated in the database via
    ``gen_random_uuid()`` (built into PostgreSQL 13+; no extension required).
  * All timestamps are timezone-aware and stored in UTC (``TIMESTAMPTZ``),
    defaulted server-side with ``now()``.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column


class UUIDPrimaryKeyMixin:
    """A PostgreSQL-native UUID primary key generated by the database."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """UTC ``created_at`` / ``updated_at`` audit columns."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class CreatedAtMixin:
    """UTC ``created_at`` only, for append-only / immutable rows."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
